# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '#about'
    weight: 1
  - name: Skills
    url: '#skills'
    weight: 2
  - name: Publications
    url: '#featured'
    weight: 3
  - name: Talks
    url: '#talks'
    weight: 4
  - name: Experience
    url: '#experience'
    weight: 5
  - name: Certificates
    url: '#accomplishments'
    weight: 6
  - name: Blog
    url: 'blog'
    weight: 7

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70
